spring:
  profiles: local
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/swimming?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      # 配置初始化大小、最小、最大 (通常来说，只需要修改initialSize、minIdle、maxActive)
      initial-size: 3
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis:  60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #http://localhost:9100/druid/datasource.html  web界面
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  port: 8888
logging:
  level:
    com.yizhiyiye.bms.dao.self: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/*Mapper.xml